/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '10/17/16 11:49 AM' with Gradle 3.1
 *
 * @author Administrator, @date 10/17/16 11:49 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
